#! /bin/bash

# Hostname for certificates.  'localhost' is good for testing,
# especially if you are behind a NAT.
HOSTNAME=localhost

# Setup the Certificate Authority and server certificates.  In
# general, this should be run once, to create these initial
# certificates, for development.

if [ -f certs/CA.crt -o -f certs/CA.key -o -f CADB.db \
	-o -f certs/SERVER.crt -o -f certs/SERVER.key ];
then
	echo "Server/CA certificates seem to already be present."
	exit 1
fi

mkdir -p certs

# Build the application.
go build || exit 1

# The HTTP server requires a private key for TLS.
openssl ecparam -name secp256r1 -genkey -out certs/SERVER.key

# Generate a self-signed X.509 certificate, containing the public key.
# This certificate should be available on any device(s) connecting to
# the HTTPS server to verify that we are communicating with the
# intended CA.
openssl req -new -x509 -sha256 -days 3650 -key certs/SERVER.key \
	-out certs/SERVER.crt \
        -subj "/O=Linaro, LTD/CN=$HOSTNAME"

# This certificate can be viewed with
# openssl x509 -in certs/SERVER.crt -noout -text

# The certificate authority also requires a key to sign certificates,
# which can be generated by the app.
./linaroca cakey generate

# **NOTE**: Certain values are hard-coded in `linaroca` when
# generating the CA certificate.  This utility may be extended to
# expose those values in the future, but at the moment the hard-coded
# values are sufficient for the proof-of-concept nature of this app.
